function toResponse(result){if(result===undefined||result instanceof Response)return result;return new Response(result?.body??'',{status:result?.statusCode??200,headers:result?.headers??{}})}
import {getDb} from './_firebase.mjs';
import {pageShell,pageMessage,card,articleUrl,imageUrl,normalizeCategory,formatDate,isPublished,publishedDate,escapeHtml,readingTime,organizationSchema,websiteSchema} from './_site.mjs';
async function getArticles(){const snap=await getDb().collection('articles').get();const list=[];snap.forEach(d=>{const a={id:d.id,...d.data()};if(isPublished(a))list.push(a)});return list.sort((a,b)=>publishedDate(b)-publishedDate(a)).slice(0,100)}
const topicSlug=c=>String(c).toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function compactRow(a,i){return `<a class="news-row reveal" href="${escapeHtml(articleUrl(a))}"><div class="news-number">${String(i+1).padStart(2,'0')}</div><img loading="lazy" src="${escapeHtml(imageUrl(a))}" alt="${escapeHtml(a.title||'Story')}" onerror="this.onerror=null;this.src='/news-placeholder.svg'"><div><div class="story-cat">${escapeHtml(normalizeCategory(a.category))}</div><h3>${escapeHtml(a.title||'Story')}</h3><div class="story-meta">${escapeHtml(formatDate(a))} · ${readingTime(a)} min read</div></div><span class="row-arrow">→</span></a>`}
function ticker(articles){const breaking=articles.filter(a=>a.breaking===true||a.isBreaking===true||String(a.priority||'').toLowerCase()==='breaking').slice(0,5);if(!breaking.length)return '';const links=breaking.map(a=>`<a href="${escapeHtml(articleUrl(a))}">${escapeHtml(a.title||'Breaking story')}</a>`).join(' <span>•</span> ');return `<div class="ticker" aria-label="Breaking news"><div class="wrap ticker-inner"><strong>BREAKING</strong><div class="ticker-track">${links} <span>•</span> ${links}</div></div></div>`}
function categoryPanel(cat,list){const items=list.filter(a=>normalizeCategory(a.category)===cat).slice(0,3);if(!items.length)return '';return `<section class="category-panel"><h3>${escapeHtml(cat)}</h3>${items.map(a=>`<a class="category-story" href="${escapeHtml(articleUrl(a))}"><img loading="lazy" src="${escapeHtml(imageUrl(a))}" alt="${escapeHtml(a.title||'Story')}" onerror="this.onerror=null;this.src='/news-placeholder.svg'"><div><h4>${escapeHtml(a.title||'Story')}</h4><span>${escapeHtml(formatDate(a))}</span></div></a>`).join('')}<a class="section-link" href="/category/${topicSlug(cat)}">More ${escapeHtml(cat)} →</a></section>`}
async function _handler(){try{const articles=await getArticles();const hero=articles[0];const side=articles.slice(1,3);const rest=articles.slice(3);const trending=[...articles].filter(a=>Number(a.views)>0).sort((a,b)=>(Number(b.views)||0)-(Number(a.views)||0)).slice(0,5);const trend=trending.length?trending:articles.slice(0,5);const picks=articles.filter(a=>a.featured===true||a.editorPick===true||a.editorsPick===true).slice(0,3);const categoryNames=['Pakistan','World','Business','Technology','Sports','Lifestyle'];
const body=hero?`${ticker(articles)}<section class="lead-section"><div class="wrap"><div class="section-kicker">Top story</div><div class="lead-grid"><a class="lead-image" href="${escapeHtml(articleUrl(hero))}"><img fetchpriority="high" src="${escapeHtml(imageUrl(hero))}" alt="${escapeHtml(hero.title||'Top story')}" onerror="this.onerror=null;this.src='/news-placeholder.svg'"><span class="image-credit">PAKBLOG</span></a><div class="lead-copy"><div class="story-cat">${escapeHtml(normalizeCategory(hero.category))}</div><h1>${escapeHtml(hero.title||'Latest news')}</h1><p>${escapeHtml(hero.excerpt||'Read the latest story from Pakblog.')}</p><div class="lead-meta"><span>${escapeHtml(hero.author||'Pakblog Desk')}</span><span>${escapeHtml(formatDate(hero))}</span><span>${readingTime(hero)} min read</span></div><a class="read-link" href="${escapeHtml(articleUrl(hero))}">Read the full story <span>→</span></a></div></div>${side.length?`<div class="lead-secondary">${side.map(a=>`<a class="secondary-lead" href="${escapeHtml(articleUrl(a))}"><img loading="lazy" src="${escapeHtml(imageUrl(a))}" alt="${escapeHtml(a.title||'Story')}" onerror="this.onerror=null;this.src='/news-placeholder.svg'"><div><div class="story-cat">${escapeHtml(normalizeCategory(a.category))}</div><h2>${escapeHtml(a.title||'Story')}</h2><div class="story-meta">${escapeHtml(formatDate(a))}</div></div></a>`).join('')}</div>`:''}</div></section>
<section class="section-block wrap"><div class="section-head"><div><div class="section-kicker">Trending now</div><h2 class="section-title">What readers are following</h2></div><span class="section-link">Updated live</span></div><div class="trend-list">${trend.map((a,i)=>`<a class="trend-item reveal" href="${escapeHtml(articleUrl(a))}"><strong>${String(i+1).padStart(2,'0')}</strong><div><div class="story-cat">${escapeHtml(normalizeCategory(a.category))}</div><h3>${escapeHtml(a.title||'Story')}</h3><span>${escapeHtml(formatDate(a))}${Number(a.views)>0?' · '+Number(a.views).toLocaleString()+' reads':''}</span></div></a>`).join('')}</div></section>
${picks.length?`<section class="section-block wrap"><div class="section-head"><div><div class="section-kicker">Editor's picks</div><h2 class="section-title">Worth your time</h2></div></div><div class="story-grid">${picks.map((a,i)=>card(a,i)).join('')}</div></section>`:''}
${rest.length?`<section class="section-block wrap"><div class="section-head"><div><div class="section-kicker">Latest</div><h2 class="section-title">The latest stories</h2></div><a class="section-link" href="/latest">View all →</a></div><div class="story-grid">${rest.slice(0,6).map((a,i)=>card(a,i)).join('')}</div></section>`:''}
${rest.length>6?`<section class="section-block wrap"><div class="split-news"><div><div class="section-head"><div><div class="section-kicker">More news</div><h2 class="section-title">Across Pakblog</h2></div></div><div class="news-list">${rest.slice(6,14).map(compactRow).join('')}</div></div></div></section>`:''}
<section class="category-section"><div class="wrap"><div class="section-head"><div><div class="section-kicker">Sections</div><h2 class="section-title">Explore the newsroom</h2></div></div><div class="category-grid">${categoryNames.map(c=>categoryPanel(c,articles)).join('')||`<div class="empty" style="grid-column:1/-1"><h2>More sections coming soon.</h2><p>Stories will appear here automatically when they are published in these sections.</p></div>`}</div></div></section>
<section class="topic-band"><div class="wrap"><div class="section-kicker">Explore</div><h2 class="section-title">All topics</h2><div class="topic-list">${['Pakistan','World','Politics','Business','Technology','Science & Health','Sports','Lifestyle','Entertainment','Education','Opinion'].map(c=>`<a class="topic" href="/category/${topicSlug(c)}">${escapeHtml(c)} <span>→</span></a>`).join('')}</div></div></section>`:pageMessage('No published stories yet','Publish an article from the Pakblog admin and it will appear here automatically.');
const itemList=articles.slice(0,12).map((a,i)=>({'@type':'ListItem','position':i+1,'url':articleUrl(a),'name':a.title||'Pakblog story'}));
const jsonLd=[organizationSchema(),websiteSchema(),{'@context':'https://schema.org','@type':'ItemList','name':'Latest Pakblog stories','itemListElement':itemList}];
return {statusCode:200,headers:{'content-type':'text/html; charset=utf-8','cache-control':'public, max-age=60, s-maxage=300'},body:pageShell({title:'Pakblog — Latest News, Pakistan & World',description:'Independent news, analysis and stories from Pakistan and around the world.',canonical:'https://pakblog.site/',body,jsonLd})};}catch(e){console.error(e);return{statusCode:500,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'},body:pageShell({title:'Pakblog — Temporarily unavailable',description:'Pakblog newsroom',canonical:'https://pakblog.site/',body:pageMessage('Pakblog is temporarily unavailable','The newsroom could not reach its article database. Please try again shortly.')})}}}
export const config={path:'/'};export default async(event,context)=>toResponse(await _handler(event,context));
